#!/usr/bin/env python

import os
import sys

Import('*')
local_env = env.Clone()

if not local_env.GetOption('clean'):
	local_env.ParseConfig('pkg-config --cflags --libs $GTK_PC')
	local_env.ParseConfig('pkg-config --cflags --libs $LUA_PC')

sources = local_env.Glob('*.cpp')

objects = local_env.StaticObject(
	source = [sources])
	
Return('objects')
