#!/usr/bin/env python

import os
import sys

Import('*')
local_env = env.Clone()

if not local_env.GetOption('clean') and not env['TOOLCHAIN'] == 'msvc':
	if not env['USE_GTK3']:
		local_env.ParseConfig('pkg-config --cflags $GIO_PC')
        else:
		local_env.ParseConfig('pkg-config --cflags $GTK_PC')

if not env['BUILD_TARGET'] == 'win32':
	sources = local_env.Glob('*.c') + local_env.Glob('*.cpp')
else:
	sources = local_env.Glob('*.cpp')

objects = local_env.StaticObject(source = [sources])
Return('objects')
