#!/usr/bin/env python

import os
import sys

Import('*')
local_env = env.Clone()

if not local_env.GetOption('clean'):
	local_env.ParseConfig('pkg-config --cflags $GTK_PC')
	if local_env.has_key('UNIQUE_PC'):
		local_env.ParseConfig('pkg-config --cflags $UNIQUE_PC')
	if local_env.has_key('DBUSGLIB_PC'):
		local_env.ParseConfig('pkg-config --cflags $DBUSGLIB_PC')

sources = []

if 'UNIQUE_PC' in local_env:
	sources.append('Unique.cpp')
elif 'DBUSGLIB_PC' in local_env:
	sources.append('UniqueDBus.cpp')
else:
	sources.append('UniqueDummy.cpp')

objects = local_env.StaticObject(source = [sources])

Return('objects')
