/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_com_google_code_gpick_SingleInstance
#define DBUS_GLIB_CLIENT_WRAPPERS_com_google_code_gpick_SingleInstance

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
com_google_code_gpick_SingleInstance_activate (DBusGProxy *proxy, GError **error)

{
  return dbus_g_proxy_call (proxy, "Activate", error, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*com_google_code_gpick_SingleInstance_activate_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
com_google_code_gpick_SingleInstance_activate_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(com_google_code_gpick_SingleInstance_activate_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
com_google_code_gpick_SingleInstance_activate_async (DBusGProxy *proxy, com_google_code_gpick_SingleInstance_activate_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "Activate", com_google_code_gpick_SingleInstance_activate_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_com_google_code_gpick_SingleInstance */

G_END_DECLS
