#!/usr/bin/env python

import os
import sys

Import('*')
local_env = env.Clone()

local_env.PrependUnique(CPPPATH = ['.'])

parser = local_env.Lemon('css_grammar.y')
lexer = local_env.Flex('css_lex.l')

sources = local_env.Glob('*.cpp')

objects = local_env.StaticObject(
	source = [sources])
	
Depends(parser, lexer)
Depends(objects, parser)
	
Return('objects')
