.TH "GPICK" "1" "" "" ""

.SH NAME
gpick \- advanced color picker

.SH SYNOPSIS
.B gpick
[\fIFILE\fR]

.SH DESCRIPTION
\fBgpick\fR starts an application and opens FILE if it is specified
.SH OPTIONS
.TP
.B \-v
Print version information
.RS
.RE
.TP
.B \-g
Window geometry.
.RS
.RE
.TP
.B \-p
Pick a color. You can insert the color at point by pressing \fBCTRL-C\fR. To hide the floating instance, press \fBESC\fR.

When this option is used, gpick is run in the background, so that all other floating instances don't start a new process. If cloosing the process is needed, then see the \fB-s\fR flag. 
.RS
.RE
.TP
.B \-s
Pick one color and exit.
.RS
.RE
.TP
.B \-o
Output picked color.
.RS
.RE
.TP
.B \-c
Converter name used for floating picker mode.
Available converters are "color_web_hex", "color_css_rgb" and "color_css_hsl".
.RS
.RE
.SH AUTHOR
Written by Albertas Vyšniauskas
