#!/usr/bin/env python

import os
import sys

Import('*')
local_env = env.Clone()
 
local_env.Append(CPPDEFINES = {'BUILD_DATE': env['GPICK_BUILD_DATE'],
	'BUILD_REVISION': env['GPICK_BUILD_REVISION'],
	'BUILD_PLATFORM': sys.platform,
	'BUILD_VERSION': env['GPICK_BUILD_VERSION'],
})

sources = local_env.Glob('*.cpp')
objects = local_env.StaticObject([sources])

Return('objects')
