#!/usr/bin/env python
Import('*')
local_env = env.Clone()

if not local_env.GetOption('clean') and not env['TOOLCHAIN'] == 'msvc':
	local_env.ParseConfig('pkg-config --cflags --libs $GTK_PC')
	local_env.ParseConfig('pkg-config --cflags --libs $LUA_PC')
	
if env['EXPERIMENTAL_CSS_PARSER']:
	local_env.Append(
		CPPDEFINES = ['EXPERIMENTAL_CSS_PARSER'],
		)
sources =  local_env.Glob('*.cpp')
objects = local_env.StaticObject(
	source = [sources])
Return('objects')
